// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demomesh.proto

package demomesh

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BackendReply struct {
	Params *BackendParams     `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Error  *BackendReplyError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// An original URL that was used to query this Backend.
	UrlRequested         string          `protobuf:"bytes,3,opt,name=urlRequested,proto3" json:"urlRequested,omitempty"`
	Backends             []*BackendReply `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BackendReply) Reset()         { *m = BackendReply{} }
func (m *BackendReply) String() string { return proto.CompactTextString(m) }
func (*BackendReply) ProtoMessage()    {}
func (*BackendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_895a88dcb64f7d09, []int{0}
}

func (m *BackendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendReply.Unmarshal(m, b)
}
func (m *BackendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendReply.Marshal(b, m, deterministic)
}
func (m *BackendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendReply.Merge(m, src)
}
func (m *BackendReply) XXX_Size() int {
	return xxx_messageInfo_BackendReply.Size(m)
}
func (m *BackendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendReply.DiscardUnknown(m)
}

var xxx_messageInfo_BackendReply proto.InternalMessageInfo

func (m *BackendReply) GetParams() *BackendParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *BackendReply) GetError() *BackendReplyError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BackendReply) GetUrlRequested() string {
	if m != nil {
		return m.UrlRequested
	}
	return ""
}

func (m *BackendReply) GetBackends() []*BackendReply {
	if m != nil {
		return m.Backends
	}
	return nil
}

// Parameters of the service as configured on the backend.
type BackendParams struct {
	// Name of the service as configured on this backend.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Port backend is configured to serve on.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// An hostname of the host service runs on.
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendParams) Reset()         { *m = BackendParams{} }
func (m *BackendParams) String() string { return proto.CompactTextString(m) }
func (*BackendParams) ProtoMessage()    {}
func (*BackendParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_895a88dcb64f7d09, []int{1}
}

func (m *BackendParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendParams.Unmarshal(m, b)
}
func (m *BackendParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendParams.Marshal(b, m, deterministic)
}
func (m *BackendParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendParams.Merge(m, src)
}
func (m *BackendParams) XXX_Size() int {
	return xxx_messageInfo_BackendParams.Size(m)
}
func (m *BackendParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendParams.DiscardUnknown(m)
}

var xxx_messageInfo_BackendParams proto.InternalMessageInfo

func (m *BackendParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackendParams) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BackendParams) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type BackendReplyError struct {
	IsError              bool     `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	ErrorString          string   `protobuf:"bytes,2,opt,name=errorString,proto3" json:"errorString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendReplyError) Reset()         { *m = BackendReplyError{} }
func (m *BackendReplyError) String() string { return proto.CompactTextString(m) }
func (*BackendReplyError) ProtoMessage()    {}
func (*BackendReplyError) Descriptor() ([]byte, []int) {
	return fileDescriptor_895a88dcb64f7d09, []int{2}
}

func (m *BackendReplyError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendReplyError.Unmarshal(m, b)
}
func (m *BackendReplyError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendReplyError.Marshal(b, m, deterministic)
}
func (m *BackendReplyError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendReplyError.Merge(m, src)
}
func (m *BackendReplyError) XXX_Size() int {
	return xxx_messageInfo_BackendReplyError.Size(m)
}
func (m *BackendReplyError) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendReplyError.DiscardUnknown(m)
}

var xxx_messageInfo_BackendReplyError proto.InternalMessageInfo

func (m *BackendReplyError) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *BackendReplyError) GetErrorString() string {
	if m != nil {
		return m.ErrorString
	}
	return ""
}

func init() {
	proto.RegisterType((*BackendReply)(nil), "demomesh.BackendReply")
	proto.RegisterType((*BackendParams)(nil), "demomesh.BackendParams")
	proto.RegisterType((*BackendReplyError)(nil), "demomesh.BackendReplyError")
}

func init() { proto.RegisterFile("demomesh.proto", fileDescriptor_895a88dcb64f7d09) }

var fileDescriptor_895a88dcb64f7d09 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4e, 0xc3, 0x40,
	0x0c, 0x85, 0x15, 0xfa, 0x43, 0xe2, 0x14, 0x24, 0xbc, 0x80, 0x11, 0x6c, 0xa2, 0xac, 0xb2, 0x2a,
	0x22, 0xdc, 0x00, 0x89, 0x35, 0xc8, 0x3d, 0x41, 0x4a, 0x2c, 0x5a, 0xd1, 0xc9, 0x0c, 0x9e, 0xe9,
	0x82, 0x2b, 0x72, 0x2a, 0x54, 0xa7, 0x8d, 0xa8, 0xda, 0x9d, 0xfd, 0xf2, 0xf9, 0xe5, 0x3d, 0x0d,
	0x5c, 0xb7, 0x6c, 0x9d, 0xe5, 0xb0, 0x9a, 0x7b, 0x71, 0xd1, 0x61, 0x7a, 0xd8, 0xcb, 0xdf, 0x04,
	0x66, 0x2f, 0xcd, 0xc7, 0x17, 0x77, 0x2d, 0xb1, 0xdf, 0xfc, 0xe0, 0x23, 0x4c, 0x7d, 0x23, 0x8d,
	0x0d, 0x26, 0x29, 0x92, 0x2a, 0xaf, 0xef, 0xe6, 0xc3, 0xed, 0x9e, 0x7b, 0xd7, 0xcf, 0xb4, 0xc7,
	0xf0, 0x09, 0x26, 0x2c, 0xe2, 0xc4, 0x5c, 0x28, 0xff, 0x70, 0xc2, 0xab, 0xef, 0xeb, 0x0e, 0xa1,
	0x9e, 0xc4, 0x12, 0x66, 0x5b, 0xd9, 0x10, 0x7f, 0x6f, 0x39, 0x44, 0x6e, 0xcd, 0xa8, 0x48, 0xaa,
	0x8c, 0x8e, 0x34, 0xac, 0x21, 0x5d, 0xf6, 0xf7, 0xc1, 0x8c, 0x8b, 0x51, 0x95, 0xd7, 0xb7, 0xe7,
	0x9d, 0x69, 0xe0, 0xca, 0x05, 0x5c, 0x1d, 0x65, 0x44, 0x84, 0x71, 0xd7, 0x58, 0xd6, 0x2a, 0x19,
	0xe9, 0xbc, 0xd3, 0xbc, 0x93, 0xa8, 0x71, 0x27, 0xa4, 0x33, 0xde, 0x43, 0xba, 0x72, 0x21, 0x2a,
	0xdb, 0x87, 0x19, 0xf6, 0xf2, 0x0d, 0x6e, 0x4e, 0x8a, 0xa0, 0x81, 0xcb, 0x75, 0xd0, 0x51, 0xbd,
	0x53, 0x3a, 0xac, 0x58, 0x40, 0xae, 0x25, 0x17, 0x51, 0xd6, 0xdd, 0xa7, 0xfe, 0x25, 0xa3, 0xff,
	0xd2, 0x72, 0xaa, 0x6f, 0xf0, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x13, 0xa8, 0x9e, 0x95,
	0x01, 0x00, 0x00,
}
